# Site settings
title: rhythmicsouls
#url: "http://laobubu.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
#baseurl: "/jekyll-theme-EasyBook" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  A good life is not necessarily a pleasurable or happy life.

# Your information
email: sudhirsinghchauhan@gmail.com
author: Sudhir Chauhan
#avatar: "//www.gravatar.com/avatar/sudhirsinghchauhan@gmail.com?d=mm&s=135"
profile: In search of a good life. If it turns out to be a happy and pleasurable one, Great!!
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
